name: stats
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - run: make lib-prod
      - run: make run-prod
      - uses: actions/upload-artifact@v3
        with:
          name: stats.csv
          path: stats.csv
