name: stats
on:
  push:
    branches:
      - develop
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - run: make lib-prod
      - run: make run-prod
      - uses: actions/upload-artifact@v3
        with:
          name: hash_stats.csv
          path: hash_stats.csv
      - uses: actions/upload-artifact@v3
        with:
          name: secretbox_stats.csv
          path: secretbox_stats.csv
      - uses: actions/upload-artifact@v3
        with:
          name: box_stats.csv
          path: box_stats.csv
